name: datapkg
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - zenodo_get>=1.6.1 # download from Zenodo
      - cdsapi>=0.7.2 # copernicus data api
      - -e . # irv_datapkg helper
  - awscli # connect to AWS, download from S3
  - black # Python formatting
  - gdal>=3.3 # command-line tools for spatial data
  - geopandas>=1.0.1 # geospatial dataframes
  - osmium-tool # openstreetmap extracts
  - pyyaml # read YAML files
  - pyogrio # faster geospatial i/o
  - bioconda::snakemake # workflow management
  - bioconda::snakefmt # Snakefile formatting
